apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: observability
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: kubesentinel
    app.kubernetes.io/component: search-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
