apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: observability
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: kubesentinel
    app.kubernetes.io/component: visualization
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
