---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: security-agents
  labels:
    app.kubernetes.io/part-of: kubesentinel
    kubesentinel.io/policy: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: security-agents
  labels:
    app.kubernetes.io/part-of: kubesentinel
    kubesentinel.io/policy: allow-dns
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: falco-health-policy
  namespace: security-agents
  labels:
    app.kubernetes.io/part-of: kubesentinel
    kubesentinel.io/policy: falco-health
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: falco
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8765
