apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: kubesentinel
    app.kubernetes.io/component: telemetry-collector
