apiVersion: v1
kind: Secret
metadata:
  name: redis-acl-secret
  namespace: kubesentinel-system
type: Opaque
stringData:
  users.acl: |
    user default off
    user producer on >PRODUCER_PASSWORD_CHANGE_ME resetchannels -@all +auth +ping +xadd ~security-events
    user consumer on >CONSUMER_PASSWORD_CHANGE_ME resetchannels -@all +auth +ping +xreadgroup +xack ~security-events
    user bootstrap on >BOOTSTRAP_PASSWORD_CHANGE_ME resetchannels -@all +auth +ping +xgroup +xinfo ~security-events
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-secret
  namespace: kubesentinel-system
type: Opaque
stringData:
  REDIS_CONSUMER_PASSWORD: "CONSUMER_PASSWORD_CHANGE_ME"
  REDIS_BOOTSTRAP_PASSWORD: "BOOTSTRAP_PASSWORD_CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-secret
  namespace: edge-pune
type: Opaque
stringData:
  REDIS_PRODUCER_PASSWORD: "PRODUCER_PASSWORD_CHANGE_ME"
