apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kubesentinel-system
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: redis-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:7.4.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - /etc/redis/redis.conf
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
              readOnly: true
            - name: acl
              mountPath: /etc/redis/users.acl
              subPath: users.acl
              readOnly: true
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: acl
          secret:
            secretName: redis-acl-secret
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
