"""Local credential bootstrapping for KubeSentinel Redis ACL and environment files."""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path


def generate_passwords() -> dict[str, str]:
    """Generate cryptographically secure distinct passwords for Redis ACL identities."""
    passwords = {
        "producer": secrets.token_urlsafe(32),
        "consumer": secrets.token_urlsafe(32),
        "bootstrap": secrets.token_urlsafe(32),
    }
    # Ensure all passwords are non-empty and mutually distinct
    values = list(passwords.values())
    if any(not v for v in values) or len(set(values)) != 3:
        raise ValueError("Generated passwords must be non-empty and distinct")
    return passwords


def render_env_local(
    passwords: dict[str, str],
    redis_host: str = "redis",
    redis_port: int = 6379,
    redis_stream: str = "security-events",
    redis_consumer_group: str = "edge-workers",
    edge_site: str = "pune",
    namespace: str = "local-compose",
    service: str = "edge-api",
) -> str:
    """Render the .env.local file content."""
    return f"""# KubeSentinel Local Environment Secrets & Configuration
# Auto-generated by: python scripts/kubesentinel.py bootstrap-local
# DO NOT COMMIT TO VERSION CONTROL

# Redis ACL Authentication Credentials
REDIS_PRODUCER_PASSWORD={passwords["producer"]}
REDIS_CONSUMER_PASSWORD={passwords["consumer"]}
REDIS_BOOTSTRAP_PASSWORD={passwords["bootstrap"]}

# Redis Connection Details
REDIS_HOST={redis_host}
REDIS_PORT={redis_port}

# Redis Stream & Consumer Group Configuration
REDIS_STREAM={redis_stream}
REDIS_CONSUMER_GROUP={redis_consumer_group}

# Edge Infrastructure Context Metadata
EDGE_SITE={edge_site}
NAMESPACE={namespace}
SERVICE={service}
"""


def render_users_acl(passwords: dict[str, str]) -> str:
    """Render the deploy/compose/redis/users.acl file content."""
    lines = [
        "user default off",
        (
            f"user producer on >{passwords['producer']} resetkeys ~security-events "
            "resetchannels -@all +auth +ping +xadd"
        ),
        (
            f"user consumer on >{passwords['consumer']} resetkeys ~security-events "
            "resetchannels -@all +auth +ping +xreadgroup +xack"
        ),
        (
            f"user bootstrap on >{passwords['bootstrap']} resetkeys ~security-events "
            "resetchannels -@all +auth +ping +xgroup +xinfo +xpending"
        ),
    ]
    return "\n".join(lines) + "\n"


def bootstrap_local(
    root_dir: Path | None = None,
    force: bool = False,
    stdout: bool = True,
) -> int:
    """Bootstrap local credentials into .env.local and deploy/compose/redis/users.acl.

    Never outputs raw secrets to stdout.
    """
    base_dir = root_dir if root_dir is not None else Path(__file__).resolve().parents[1]
    env_path = base_dir / ".env.local"
    acl_dir = base_dir / "deploy" / "compose" / "redis"
    acl_path = acl_dir / "users.acl"

    existing_files: list[str] = []
    if env_path.exists():
        existing_files.append(str(env_path.relative_to(base_dir)))
    if acl_path.exists():
        existing_files.append(str(acl_path.relative_to(base_dir)))

    if existing_files and not force:
        msg = (
            f"[bootstrap-local] Error: Destination files already exist: {', '.join(existing_files)}.\n"
            "Pass --force to overwrite existing credentials."
        )
        if stdout:
            print(msg, file=sys.stderr)
        return 1

    passwords = generate_passwords()
    env_content = render_env_local(passwords)
    acl_content = render_users_acl(passwords)

    # Write .env.local with secure permissions and UTF-8
    env_path.write_text(env_content, encoding="utf-8")
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass

    # Ensure target directory exists and write users.acl
    acl_dir.mkdir(parents=True, exist_ok=True)
    acl_path.write_text(acl_content, encoding="utf-8")
    try:
        os.chmod(acl_path, 0o600)
    except OSError:
        pass

    if stdout:
        print("[bootstrap-local] Local bootstrap credentials successfully generated:")
        print(f"  - Environment: {env_path.relative_to(base_dir)}")
        print(f"  - Redis ACL:   {acl_path.relative_to(base_dir)}")
        print("Least-privilege Redis ACL rules applied (default user off).")
        print("Credentials protected; use --force to regenerate.")

    return 0
